# Build script for Travis CI
#

# use xenial distribution
dist: xenial

# no need to check for oracle's java
language: python

# speed up builds by caching pip, miniconda
cache:
  directories:
    - "$HOME/.cache/pip"

# Maintain only one version of the docs, for now
branches:
  only:
  - master

# added to make logs look cleaner, crisper, certified fresh
before_install: unset _JAVA_OPTIONS 

# we need javapshinx to generate javadocs
install: true
- pip install javasphinx

# keeping complicated scripts separate is not much, but it's honest work
script: generate-javadocs.py -r repositories.txt -t .index.rst.template -o docs

# commit and push changes
deploy:
  # our "deployment" is to commit and push changes done in the docs folder
- skip_cleanup: true
  provider: script
  script: push-changes.sh docs
  on:
    branch: master
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'

# GitHub access credentials (username/token)
env:
  global:
    - secure: "kschiefcCbkZhDHvuSi2AGEAG95OFKO8SJal8MzKm+Sqivi8stwClQ3KBYnbKJ3WswG12GkuAPSScCme5sDjhKw2N/pML8O/+VtuqGNE7HtNQQgRhuMZr2A6Wx0X+7I80IT8/BMrpZnyuUx/eXkDe/jt7hZXiCqQzlq8XPQCaI331kJ792gI/pru4mx7f1USu7dBFG3bOBbwcrpUzbF3IdxN318ge8tVv60bMhXv+BDbiN8sgGKHL7TyfHIw8gU+n+toSFnhhDP31ojMMu5NHyyTfXt9/vFf5yMnRP1HVT8OGzVGE/PKpwPssZ41z9MvDZOHIvnw5cVTQFeZbyrNL4W46iUNhouODCBarhvsfVgGerlpomCGlP4yUP6JoB9mbvjBZsQpoIC07gy9jghJa3mPSaqUV3IMA3l/GRDo9n7EC1M26Qy8qVmz4odyYM1Ih/60tcgaPLy1SZnW4PIhJUBEA0/o5BXQwmdmdeJ1DoQoxHqBkrM/lIBM+Y8jXEPagTQ6Xb0jhwcj0B5vm6piw4jlKTbeftyB64yCNkRGfZRhGguFkwFa9kCsswUYtFKlaoSCwaJvlo5m0d66ykKU/NjXDnBQksMyxq0ThWn6AWN0OInlmiYaQqe0B7ryU64Ohm+qV/5hEpFd1G1IYTlcLnOeWpO2DJvwHqE1HrVKDE0="
    - secure: "oR/d0yw/ts/j8d3+41JKxOKUaljgrZWI7tBCHw7qtmHLiQUjsRYjaiJb/M9aUmd9rLVEm+Aqwnke+Haz1/NMAOJv73pXA9VH5NzTQvzhaanxk+ORrNYh2eYdx/dcD5G8IOf76Y61Wyq/eegivTQHzuSW3fzorteDLekzPZmSnWKy1T/1AijU+endvQKUuYpmPECEQw+SP+DJzNC1mCmIajknAB9SwIKKe5rA7YR9uxuT9dwdSciztww26L4iW9YMSSyu2gsgqZJspDhLvwSd+8aaDEyUHMMBpozLVhmdokAradXM1v3Fvi0Z/ITstjV9T+A10C1rxT6mbjPPzOI3IMhEHei4uJOaFNrlpTJ/G6DJXfjrW5BLECm1eCmrQwnKvyEwU6rG8i/WW9dJ/9aCXglpNZYRk4ARFZb3vJ9IbJVC+PeY5oRZLIuSgeLwPiSWUsG6TQhnv2ZgwAdGF+bC/IQ3CNX5rdl8tfOVqCD10oj/KY5NsT76XzEAj6qEX0yML6SXBANCZYXwLRrN+t5mnfxe3hhBGWgMT0QNsPkFlCX//tHtFHz4R3qc87XhTjZJzPym85nXaotPAO/tDQfo7gjxc8dfIlaLRHL3if+q1gVsPCQaCYAKnU6iGo9JnZ94L7cuXBigxFHRpwSM4KqweP/QHGf2Ofrbrm6QwKCbScI="
